import Providers from "@/providers/Providers";
import "./global.css";
import cn from "@/utils/functions/cn";
import localFont from "next/font/local";
import QueryClientProviders from "@/providers/QueryClientProviders";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "DevRiser | Web Dashboard",
  description: "Generated by Next.js",
};

const monaSans = localFont({
  src: [
    {
      path: "./../../assets/fonts/Mona-Sans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../assets/fonts/Mona-Sans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../assets/fonts/Mona-Sans-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../../assets/fonts/Mona-Sans-Bold.woff2",
      weight: "bold",
      style: "normal",
    },
  ],
  variable: "--font-mona-sans",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${cn(monaSans.variable, "font-mono-sans")} h-screen w-full`}
      >
        <Providers>
          <QueryClientProviders>
            <div className="flex w-full h-full relative">{children}</div>
            <Toaster />
          </QueryClientProviders>
        </Providers>
      </body>
    </html>
  );
}
